### ISSUE TITLE
Suggestion: Turn font settings into variables

### ISSUE THREAD

**Issue by woerndl** [saimnaveediqbal/thesis-NTNU-typst#1]
Hey Saim,

thanks for sharing your template. Do you think it would make sense to turn the font settings into variables, for people who use the template outside the NTNU context?

I couldn't figure out how to change the font for the title and abstract. Main text can be overwritten globally.

Turning it into:

```
  font: "Charter",
  raw-font: "DejaVu Sans Mono",
  paper-size: "a4",
```

and:

```
  // Set text fonts and sizes
  set text(font: font, size: 11pt)
  show raw: set text(font: raw-font, size: 9pt)
```

Might make it easier for anyone trying to change the font settings?

**Comment by saimnaveediqbal** [comment]
Hm, feels a bit unconventional, as font choice is a large part of the template. But I don't see any problem with more customization, so I might add if I have time

**Comment by woerndl** [comment]
I think changing the suggested 4 lines would already do the trick, because other settings like tracking, spacing, font features, etc., can easily be set on a per-document basis, since they aren't set in the `nifty-ntnu-thesis` function.

However, I couldn't figure out how to change the `set text` in the `#show` call yet. If there's an easy way that I'm just not aware of, there might be no need for my suggestion. If there isn't, simply wanting to change the font would currently make it necessary to duplicate the template (there probably is a way, maybe wrapping the `#show` call or something, but I don't know how).
